Changes allowing more flexibility with repos and CodeBuild
plus3it/github-codebuild-webhook pull request #6
Opened 2018-02-08 22:08 UTC by YakDriver

Many thing is 3 new variables: CODEBUILD_USE_VERSION, CODEBUILD_GIT_REPO_VAR, and CODEBUILD_GIT_REF_VAR, all optional

2018-02-09 11:19 UTC, lorengordon commented on .gitignore
> +envvars.sh
How about putting these files into ./private and having just one entry here for `.private`? That way it works for anyone, regardless of the filenames they choose to use.

2018-02-09 11:23 UTC, lorengordon commented on README.md
> +export CB_EXTERNAL_BUILDSPEC=false # If "false", webhook will not have CodeBuild submit source version in buildspec.yml request (useful if in 2 different repos or you want to use the most recent comm
The default should be "true" to retain prior behavior.

Also, I think the description here is too much detail. Should be sufficient to say something like "Set to false if the repo for the CodeBuild project itself is different from the repo where the webhook will be created"

2018-02-09 11:24 UTC, lorengordon commented on README.md
> +export CB_GIT_REPO_ENV=REPO_TO_BUILD # Name of env var to pass to CodeBuild with repo triggering build
"Name of ENV variable that your CodeBuild project uses to know which repo to clone. Use in conjunction with CB_EXTERNAL_BUILDSPEC."

2018-02-09 11:24 UTC, lorengordon commented on README.md
> +export CB_GIT_REF_ENV=REF_TO_BUILD # Name of env var to pass to CodeBuild with PR# triggering build
"Name of ENV variable that your CodeBuild project uses to know which git ref to checkout. For use with CB_EXTERNAL_BUILDSPEC."

2018-02-09 11:25 UTC, lorengordon commented on envvars
> +#!/bin/bash
This file should be hidden in .private

2018-02-09 11:28 UTC, lorengordon commented on README.md
> +export CB_EXTERNAL_BUILDSPEC=false # If "false", webhook will not have CodeBuild submit source version in buildspec.yml request (useful if in 2 different repos or you want to use the most recent comm
Oops, we flipped the logic, "false" is the correct default. "Set to _true` if ..."

2018-02-09 11:35 UTC, lorengordon commented on handler.js
> +// if set to true, CodeBuild will not include PR number in request from buildspec from git
"Controls whether the `sourceVersion` parameter is set to the pull request and passed to the CodeBuild job. Set to true if the repo for the CodeBuild project itself is different from the repo where the webhook will be created"

2018-02-09 12:16 UTC, lorengordon commented on handler.js
> +      if (buildOptions.cbGitRepoEnv && buildOptions.cbGitRefEnv ) {
The logic around this needs a bit of consideration. A git ref is not _required_ when cloning a repo. The clone will simply use the repo's default branch.

Also, what is the rationale for not nesting this test in the `!buildOptions.cbExternalBuildspec` test? I can't think of any reason to use these params separately from that param.

2018-02-09 12:18 UTC, lorengordon commented on serverless.yml
> +    cbExternalBuildspec: ""
default to "false"

2018-02-09 12:20 UTC, lorengordon commented on serverless.yml
> +      Description: If true, CodeBuild will not send "sourceVersion" with request for buildspec (e.g., allowing buildspec to be in an external repo not on same PR number)
"Controls whether the sourceVersion parameter is set to the pull request and passed to the CodeBuild job. Set to true if the repo for the CodeBuild project itself is different from the repo where the webhook will be created"

2018-02-09 12:20 UTC, lorengordon commented on serverless.yml
> +      Description: Name of the env used to pass repo clone URL to CodeBuild (optional, if not set, not passed)
"(Optional) Name of ENV variable that your CodeBuild project uses to know which repo to clone. For use with CB_EXTERNAL_BUILDSPEC."

2018-02-09 12:20 UTC, lorengordon commented on serverless.yml
> +      Description: Name of the env used to pass PR number to CodeBuild (optional, if not set, not passed)
"(Optional) Name of ENV variable that your CodeBuild project uses to know which git ref to checkout. For use with CB_EXTERNAL_BUILDSPEC."

2018-02-09 12:24 UTC, lorengordon requested changes
Ok, left some comments mostly about refining the descriptions.

I do think the logic testing the git repo and ref envs needs a little more consideration, since only the repo is technically required. Also, I don't see any particular reason to use these variables separately from cb_external_buildspec, so I think the tests can be nested or combined.

2018-02-09 12:26 UTC, lorengordon commented
Oh, and please squash/rebase the extraneous commits, most specifically so that any files that are not part of the repo do not appear in the commit history.

2018-02-16 17:33 UTC, YakDriver commented
Changes suggested have been incorporated, specifically descriptions of new variables and allowing for ref to be optional if repo is used (already did it that way on the other side, not sure why it was this way on this side).

2018-02-16 17:45 UTC, lorengordon reviewed
Awesome, just one last change....

2018-02-16 17:45 UTC, lorengordon commented on handler.js
> +        console.log("Not using the source version! Will likely use most-recently commited buildspec.yml instead. (Use CB_EXTERNAL_BUILDSPEC=true parameter to change.)");
The message here I think can be more straightforward. "Using an external buildspec. Will not pass `sourceVersion` when starting the CodeBuild job. Set CB_EXTERNAL_BUILDSPEC=false to change."

2018-02-16 18:09 UTC, YakDriver commented
Revised

2018-02-16 18:13 UTC, lorengordon approved these changes

2018-02-16 18:13 UTC, merged